In [14]:
import numpy as np
x = np.array([[[[1,2], [3,4]], [[5,6],[7,8]], [[9,10], [11,12]]], [[[13,14], [15,16]], [[17,18],[19,20]], [[21,22], [23,24]]]])

In [15]:
x

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]],

        [[ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16]],

        [[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [16]:
x.shape

(2, 3, 2, 2)

In [18]:
y = x.reshape(6,4)
y.shape

(6, 4)

In [19]:
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [23]:
z = x.reshape(2,4,3)
z.shape

(2, 4, 3)

In [24]:
z

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [25]:
yy = y.reshape(3,2,2,2)
yy.shape

(3, 2, 2, 2)

In [26]:
yy

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])

In [27]:
zz = z.reshape(3,2,2,2)
zz.shape

(3, 2, 2, 2)

In [28]:
zz

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]],


       [[[17, 18],
         [19, 20]],

        [[21, 22],
         [23, 24]]]])